pipeline {
    agent any

    tools {
        jdk 'java-11'
        maven 'maven'
    }

    environment {
        IMAGE_NAME = "sunilresume-app"
        IMAGE_TAG  = "1"
    }

    stages {

        stage('Git Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Sunilo7/jenkins-ci-with-docker-push-to-dockerhub.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker stop c1 || true
                docker rm c1 || true
                docker run -d --name c1 -p 9000:8080 ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'docker-hub-credentials',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {
                    sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                }
            }
        }

        stage('Tag & Push Image to Docker Hub') {
            steps {
                sh '''
                docker tag ${IMAGE_NAME}:${IMAGE_TAG} $DOCKER_USERNAME/${IMAGE_NAME}:${IMAGE_TAG}
                docker push $DOCKER_USERNAME/${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }
    }
}
